#!/usr/bin/env bash
# COnfigure HAProxy on the Load balancer
apt-get update
apt-get install -y haproxy=1.6.\*
echo -e "\nbackend web-backend\n\tbalance roundrobin\n\tserver web1 35.231.195.130:80 check\n\tserver web2 35.237.238.148:80 check\n" >> /etc/haproxy/haproxy.cfg
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n" >> /etc/haproxy/haproxy.cfg
service haproxy restart
